### ISSUE TITLE
Database migration fails

### ISSUE THREAD

**Issue by a-mair** [pytrainer/pytrainer#140]
Hi,

after a long time (~1.5 years) I tried to update pytrainer. But it fails to start:

>  data_path: /usr/share/pytrainer/
gettext_path: /usr/share/locale
  site_path: /usr/lib/python2.7/site-packages
Gtk-Message: Failed to load module "canberra-gtk-module"
Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/pytrainer", line 85, in <module>
    main()
  File "/usr/lib/python-exec/python2.7/pytrainer", line 82, in main
    pytrainer = pyTrainer(None, data_path)
  File "/usr/lib/python2.7/site-packages/pytrainer/main.py", line 74, in __init__
    initialize_data(self.ddbb, self.environment.conf_dir)
  File "/usr/lib/python2.7/site-packages/pytrainer/upgrade/data.py", line 30, in initialize_data
    InstalledData(migratable_db, ddbb, LegacyVersionProvider(conf_dir), UpgradeContext(conf_dir, db_url)).update_to_current()
  File "/usr/lib/python2.7/site-packages/pytrainer/upgrade/data.py", line 64, in update_to_current
    data_state.update_to_current(self)
  File "/usr/lib/python2.7/site-packages/pytrainer/upgrade/data.py", line 169, in update_to_current
    self._update_function(installed_data)
  File "/usr/lib/python2.7/site-packages/pytrainer/upgrade/data.py", line 176, in _update_stale
    data.upgrade()
  File "/usr/lib/python2.7/site-packages/pytrainer/upgrade/data.py", line 146, in upgrade
    self._migratable_db.upgrade()
  File "/usr/lib/python2.7/site-packages/pytrainer/upgrade/migratedb.py", line 86, in upgrade
    upgrade(self._db_url, self._repository_path)
  File "/usr/lib/python2.7/site-packages/migrate/versioning/api.py", line 186, in upgrade
    return _migrate(url, repository, version, upgrade=True, err=err, **opts)
  File "<decorator-gen-15>", line 2, in _migrate
  File "/usr/lib/python2.7/site-packages/migrate/versioning/util/__init__.py", line 167, in with_engine
    return f(*a, **kw)
  File "/usr/lib/python2.7/site-packages/migrate/versioning/api.py", line 366, in _migrate
    schema.runchange(ver, change, changeset.step)
  File "/usr/lib/python2.7/site-packages/migrate/versioning/schema.py", line 93, in runchange
    change.run(self.engine, step)
  File "/usr/lib/python2.7/site-packages/migrate/versioning/script/py.py", line 148, in run
    script_func(engine)
  File "/usr/lib/python2.7/site-packages/pytrainer/upgrade/versions/015_match_sqlalchemy.py", line 84, in upgrade
    laps_records_fkey.create()
  File "/usr/lib/python2.7/site-packages/migrate/changeset/constraint.py", line 44, in create
    self.__do_imports('constraintgenerator', *a, **kw)
  File "/usr/lib/python2.7/site-packages/migrate/changeset/constraint.py", line 32, in __do_imports
    run_single_visitor(engine, visitorcallable, self, *a, **kw)
  File "/usr/lib/python2.7/site-packages/migrate/changeset/databases/visitor.py", line 85, in run_single_visitor
    fn(element, **kwargs)
  File "/usr/lib/python2.7/site-packages/migrate/changeset/databases/sqlite.py", line 183, in visit_migrate_foreign_key_constraint
    self.recreate_table(p[0].table)
  File "/usr/lib/python2.7/site-packages/migrate/changeset/databases/sqlite.py", line 106, in recreate_table
    self.execute()
  File "/usr/lib/python2.7/site-packages/migrate/changeset/ansisql.py", line 44, in execute
    return self.connection.execute(self.buffer.getvalue())
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 939, in execute
    return self._execute_text(object, multiparams, params)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1097, in _execute_text
    statement, parameters
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) datatype mismatch [SQL: u'INSERT INTO laps SELECT * from migration_tmp']

The old version I had been running has been taken straight from GIT ~1.5 years ago. I try to get v1.12.1 up and running. I also tried previous releases, but the last stable release working here is 1.10.0.

Any ideas what's going wrong here?

Best regards,
Andreas

**Comment by viiru-** [comment]
I was fairly worried that this would happen to a number of users. Before version 1.12.0 the pytrainer database did not have any constraints, so any bug in the code could corrupt the database and that corruption could in many cases go undetected for a long time. In this version a number of constraints were added, making sure that the database contents would remain valid even if there were programming errors.

In your case running the migrations that add these constraints fail, meaning that the contents of your database is corrupt one way or the other. Sadly sqlalchemy-migrate isn't great at reporting what exactly went wrong, and in cases like this it also leaves the database in an inconsistent state (some of the migrations have been applied, others have not). For this reason a backup of the database file is created before applying, see the .pytrainer directory to find that.

In this case we can see that migrations fail for the laps table, where the only relevant change that was made was adding a foreign key constraint between laps and records. We can thus tell that either you have a lap in the database where the record it refers to doesn't exist, or (more likely based on the error message) there is a lap there where the record column is null (or otherwise non-integer).

You can copy the backup back into place and try to look for and manually repair (perhaps by simply deleting the invalid row) it.

**Comment by a-mair** [comment]
I've check laps table but there's no non-integer value in the records column.
The laps table has a value in the record column which has no matching entry in the id_record column of the records table. I restored the DB backup and deleted that row in the laps table. But pytrainer still fails:

> data_path: /usr/share/pytrainer/
gettext_path: /usr/share/locale
site_path: /usr/lib/python2.7/site-packages
Gtk-Message: Failed to load module "canberra-gtk-module"
Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/pytrainer", line 85, in <module>
    main()
  File "/usr/lib/python-exec/python2.7/pytrainer", line 82, in main
    pytrainer = pyTrainer(None, data_path)
  File "/usr/lib/python2.7/site-packages/pytrainer/main.py", line 74, in __init__
    initialize_data(self.ddbb, self.environment.conf_dir)
  File "/usr/lib/python2.7/site-packages/pytrainer/upgrade/data.py", line 30, in initialize_data
    InstalledData(migratable_db, ddbb, LegacyVersionProvider(conf_dir), UpgradeContext(conf_dir, db_url)).update_to_current()
  File "/usr/lib/python2.7/site-packages/pytrainer/upgrade/data.py", line 64, in update_to_current
    data_state.update_to_current(self)
  File "/usr/lib/python2.7/site-packages/pytrainer/upgrade/data.py", line 169, in update_to_current
    self._update_function(installed_data)
  File "/usr/lib/python2.7/site-packages/pytrainer/upgrade/data.py", line 176, in _update_stale
    data.upgrade()
  File "/usr/lib/python2.7/site-packages/pytrainer/upgrade/data.py", line 146, in upgrade
    self._migratable_db.upgrade()
  File "/usr/lib/python2.7/site-packages/pytrainer/upgrade/migratedb.py", line 86, in upgrade
    upgrade(self._db_url, self._repository_path)
  File "/usr/lib/python2.7/site-packages/migrate/versioning/api.py", line 186, in upgrade
    return _migrate(url, repository, version, upgrade=True, err=err, **opts)
  File "<decorator-gen-15>", line 2, in _migrate
  File "/usr/lib/python2.7/site-packages/migrate/versioning/util/__init__.py", line 167, in with_engine
    return f(*a, **kw)
  File "/usr/lib/python2.7/site-packages/migrate/versioning/api.py", line 366, in _migrate
    schema.runchange(ver, change, changeset.step)
  File "/usr/lib/python2.7/site-packages/migrate/versioning/schema.py", line 93, in runchange
    change.run(self.engine, step)
  File "/usr/lib/python2.7/site-packages/migrate/versioning/script/py.py", line 148, in run
    script_func(engine)
  File "/usr/lib/python2.7/site-packages/pytrainer/upgrade/versions/015_match_sqlalchemy.py", line 84, in upgrade
    laps_records_fkey.create()
  File "/usr/lib/python2.7/site-packages/migrate/changeset/constraint.py", line 44, in create
    self.__do_imports('constraintgenerator', *a, **kw)
  File "/usr/lib/python2.7/site-packages/migrate/changeset/constraint.py", line 32, in __do_imports
    run_single_visitor(engine, visitorcallable, self, *a, **kw)
  File "/usr/lib/python2.7/site-packages/migrate/changeset/databases/visitor.py", line 85, in run_single_visitor
    fn(element, **kwargs)
  File "/usr/lib/python2.7/site-packages/migrate/changeset/databases/sqlite.py", line 183, in visit_migrate_foreign_key_constraint
    self.recreate_table(p[0].table)
  File "/usr/lib/python2.7/site-packages/migrate/changeset/databases/sqlite.py", line 106, in recreate_table
    self.execute()
  File "/usr/lib/python2.7/site-packages/migrate/changeset/ansisql.py", line 44, in execute
    return self.connection.execute(self.buffer.getvalue())
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 939, in execute
    return self._execute_text(object, multiparams, params)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1097, in _execute_text
    statement, parameters
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) datatype mismatch [SQL: u'INSERT INTO laps SELECT * from migration_tmp']

Did I miss something?
BTW: I've some records without laps, but that shouldn't be a problem, right?

**Comment by viiru-** [comment]
No, records without laps should not be a problem here.

You could try to run that failing SQL statement manually to see if sqlite give better error output (I'd guess it should).

**Comment by viiru-** [comment]
The one in your traceback above, "INSERT INTO laps SELECT * from migration_tmp".

**Comment by a-mair** [comment]
OK, the result:
> sqlite> INSERT INTO laps SELECT * from migration_tmp;
Error: datatype mismatch

**Comment by viiru-** [comment]
Bah. So migrate did output the entire error message from sqlite, which is the one being too terse to be of any use.

**Comment by a-mair** [comment]
I've looked into the source "laps" table. 907 rows have nothing in "id_lap", only 346 rows have numbers. I guess that breaks the "id_lap" column definition: id_lap INTEGER NOT NULL

Any idea how to fix that?

**Comment by viiru-** [comment]
Huh. That is major corruption indeed. Any unique integer will do, so I guess you could generate more or less random numbers? I don't have anything suitable ready to go, though.

**Comment by privong** [comment]
I guess a possible difference in my case was that `colors` in the `sports` table were all filled with text values.

**Comment by a-mair** [comment]
@viiru- , @privong 
I've done some tests using sqlite3. First I've filled the "id_laps" with "rowid" (unique numbers), so that that column can act as a primary key and is "NOT NULL". Then I played with the "CREATE TABLE laps" call.
In the end it showed that the only thing that brings "Error: datatype mismatch" is the "PRIMARY KEY (id_lap)" part. But I have no idea why.

Any ideas?

**Comment by a-mair** [comment]
@viiru- @privong 

Any ideas on how to fix my database?

**Comment by viiru-** [comment]
> In the end it showed that the only thing that brings "Error: datatype mismatch" is the "PRIMARY KEY (id_lap)" part. But I have no idea why.

In that case I'd start by checking that the id_lap column on every row of your table is a. set and b. set to an integer and not a string (I think you already checked them all for NULL). Sqlite is very lax with types, but probably not in the case of a primary key (see here for the documentation about the magic related to integer primary keys: https://www.sqlite.org/lang_createtable.html#rowid).

**Comment by a-mair** [comment]
No more DB migration errors, but now I get:
> data_path: /usr/share/pytrainer/
gettext_path: /usr/share/locale
site_path: /usr/lib/python2.7/site-packages
/usr/lib/python2.7/site-packages/pytrainer/gui/SimpleGladeApp.py:30: GtkWarning: GtkFrame does not have a property called padding
  self._builder.add_from_file(file_path)
/usr/lib/python2.7/site-packages/pytrainer/gui/SimpleGladeApp.py:30: GtkWarning: GtkFrame does not have a property called expand
  self._builder.add_from_file(file_path)
/usr/lib/python2.7/site-packages/pytrainer/gui/SimpleGladeApp.py:30: GtkWarning: GtkFrame does not have a property called fill
  self._builder.add_from_file(file_path)
/usr/lib/python2.7/site-packages/pytrainer/gui/SimpleGladeApp.py:30: GtkWarning: GtkFrame does not have a property called position
  self._builder.add_from_file(file_path)
Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/pytrainer", line 85, in <module>
    main()
  File "/usr/lib/python-exec/python2.7/pytrainer", line 82, in main
    pytrainer = pyTrainer(None, data_path)
  File "/usr/lib/python2.7/site-packages/pytrainer/main.py", line 105, in __init__
    self.loadPlugins()
  File "/usr/lib/python2.7/site-packages/pytrainer/main.py", line 197, in loadPlugins
    self.windowmain.addImportPlugin(txtbutton)
  File "/usr/lib/python2.7/site-packages/pytrainer/gui/windowmain.py", line 244, in addImportPlugin
    self.menuitem1_menu.insert(button,3)
  File "/usr/lib/python2.7/site-packages/pytrainer/gui/SimpleGladeApp.py", line 52, in __getattr__
    raise AttributeError, data_name
AttributeError: menuitem1_menu

Any ideas what's wrong now?

**Comment by viiru-** [comment]
Apparently there is a special menu which only appears if one of two plugins is enabled. That menu did not survive the automatic conversion from Glade files to GTK Builder xml, the same thing happened to some other bit as well that needed to be manually restored. I can reproduce this, and will take a look at it.

**Comment by a-mair** [comment]
I've played DB migration this afternoon. I called the sqlite3 client using the DB file I got after pytrainer failed to migrate. That's the result:
`INSERT INTO laps SELECT * from migration_tmp;` doesn't work due to different table layout of "laps" and "migration_temp".

You can see different column ordering:
`CREATE TABLE IF NOT EXISTS "migration_tmp" ("elapsed_time" VARCHAR(20), "record" INTEGER, "end_lon" FLOAT, "start_lon" FLOAT, "end_lat" FLOAT, "distance" FLOAT, "id_lap" INTEGER, "calories" INT, "start_lat" FLOAT, "lap_number" INTEGER, "laptrigger" VARCHAR(9), "intensity" VARCHAR(7), "avg_hr" INT, "max_hr" INT, "max_speed" FLOAT, "comments" TEXT);`
`CREATE TABLE laps (distance FLOAT, end_lon FLOAT, lap_number INTEGER, start_lon FLOAT, id_lap INTEGER NOT NULL, calories INTEGER, avg_hr INTEGER, comments TEXT, elapsed_time VARCHAR(20), record INTEGER, intensity VARCHAR(7), laptrigger VARCHAR(9), max_hr INTEGER, end_lat FLOAT, start_lat FLOAT, max_speed FLOAT, PRIMARY KEY (id_lap), FOREIGN KEY(record) REFERENCES records (id_record));`

It works if I modify the INSERT like this:
`INSERT INTO laps SELECT distance,end_lon,lap_number,start_lon,id_lap,calories,avg_hr,comments,elapsed_time,record,intensity,laptrigger,max_hr,end_lat,start_lat,max_speed from migration_tmp;`

I wonder how the pytrainer sources can be changed to get the working INSERT call to run.
I also wonder why nobody else faces that problem.
Any ideas?

**Comment by viiru-** [comment]
Hmm. I assume migrate creates a copy of the existing laps table, as it is. It seems that the version of pytrainer you created your database on did something different than the versions that have been tested.

I'm not at all sure there is anything we can do here, the problem being caused by historical issues in former versions and the solution would be to make migrate more robust (generate the select with a list of columns). You can probably offer that project patches.

**Comment by a-mair** [comment]
> Hmm. I assume migrate creates a copy of the existing laps table, as it is. It seems that the version of pytrainer you created your database on did something different than the versions that have been tested.

I think that too. I've also created a new DB using another user's account with pytrainer 1.10.0 and the "laps" table looks the same like mine.

> You can probably offer that project patches.

I would if I could but I don't know where to start.

**Comment by viiru-** [comment]
From looking at the original code, the order of columns depends probably at least on the version of the Python interpreter used and the OS it runs on (it relies on the order of the fields in a dict, which is explicitly documented as being something you cannot rely on).

I hadn't realised that the original code was this bad (I knew it was bad, which is why I replaced it). I'm not sure what can be done to retroactively fix things, though. Any attempt at fixing this with migrate as it is will fail (as proven by the problem you see, migrate can't handle the columns being in a random order).

**Comment by viiru-** [comment]
Of course there is the option of not doing the migration, and leaving existing databases forever as they are. That would work for this version, but will not work for following versions which make actual changes (this migration just adds a couple of constraints and indexes).

**Comment by a-mair** [comment]
> Any attempt at fixing this with migrate as it is will fail

For the records and anybody interested, this is how I fixed it. It should fix any column ordering for the "laps" and "sports" table:
```SQL
ALTER TABLE laps RENAME TO laps_temp;
CREATE TABLE laps (distance FLOAT, end_lon FLOAT, lap_number INTEGER, start_lon FLOAT, id_lap INTEGER, calories INTEGER, avg_hr INTEGER, comments TEXT, elapsed_time VARCHAR(20), record INTEGER, intensity VARCHAR(7), laptrigger VARCHAR(9), max_hr INTEGER, end_lat FLOAT, start_lat FLOAT, max_speed FLOAT);
INSERT INTO laps SELECT distance,end_lon,lap_number,start_lon,id_lap,calories,avg_hr,comments,elapsed_time,record,intensity,laptrigger,max_hr,end_lat,start_lat,max_speed from laps_temp;
DROP TABLE laps_temp;
UPDATE laps SET id_lap = rowid;
ALTER TABLE sports RENAME TO sports_temp;
CREATE TABLE sports (id_sports INTEGER NOT NULL, name VARCHAR(100), weight FLOAT, color CHAR(6) NOT NULL,  max_pace INTEGER, met FLOAT, PRIMARY KEY (id_sports));
INSERT INTO sports SELECT id_sports,name,weight,color,max_pace,met FROM sports_temp;
DROP TABLE sports_temp;
VACUUM;
```
Maybe you can run something like that for any table to bring them to the expected column order before 015_match_sqlalchemy.py runs?

> Of course there is the option of not doing the migration, and leaving existing databases forever as they are.

No! Please don't.

> Apparently there is a special menu which only appears if one of two plugins is enabled. That menu did not survive the automatic conversion from Glade files to GTK Builder xml, the same thing happened to some other bit as well that needed to be manually restored. I can reproduce this, and will take a look at it.

Is there anything I can do to enable those plugin(s) without running pytrainer?

**Comment by a-mair** [comment]
One more thing:
`laptrigger VARCHAR(9)` is too short. My laps table holds the values time, manual and laptrigger. "laptrigger" has 10 characters.

It doesn't harm in sqlite as it uses TEXT  here, but it should be fixed while you clean the database schema.

**Comment by viiru-** [comment]
Andreas <notifications@github.com> writes:
>> Any attempt at fixing this with migrate as it is will fail
>
> For the records and anybody interested, this is how I fixed it. It should fix
> any column ordering for the "laps" and "sports" table:
> ```SQL
> ALTER TABLE laps RENAME TO laps_temp;
> CREATE TABLE laps (distance FLOAT, end_lon FLOAT, lap_number INTEGER,
> start_lon FLOAT, id_lap INTEGER, calories INTEGER, avg_hr INTEGER, comments
> TEXT, elapsed_time VARCHAR(20), record INTEGER, intensity VARCHAR(7),
> laptrigger VARCHAR(9), max_hr INTEGER, end_lat FLOAT, start_lat FLOAT,
> max_speed FLOAT);
> INSERT INTO laps SELECT
> distance,end_lon,lap_number,start_lon,id_lap,calories,avg_hr,comments,elapsed_time,record,intensity,laptrigger,max_hr,end_lat,start_lat,max_speed
> from laps_temp;
> DROP TABLE laps_temp;
> UPDATE laps SET id_lap = rowid;
> ALTER TABLE sports RENAME TO sports_temp;
> CREATE TABLE sports (id_sports INTEGER NOT NULL, name VARCHAR(100), weight
> FLOAT, color CHAR(6) NOT NULL, max_pace INTEGER, met FLOAT, PRIMARY KEY
> (id_sports));
> INSERT INTO sports SELECT id_sports,name,weight,color,max_pace,met FROM sports_temp;
> DROP TABLE sports_temp;
> VACUUM;
> ```
> Maybe you can run something like that for any table to bring them to the
> expected column order before 015_match_sqlalchemy.py runs?

I would probably accept reasonably non-invasive patches doing this. I'm
not sure how to hook between specific migrations, though. I assume there
will be problems if we try to do this before running the other 14
migrations. Also keeping in mind that this should only be done sqlite
databases (if there are Mysql users they don't need this, Mysql has
alter table and doesn't do the "create temp table, move data, create new
table" dance that is failing).

Any hints on what is special about your systems that get this
alternative column order? Could we try to detect that?

>> Apparently there is a special menu which only appears if one of two plugins
>> is enabled. That menu did not survive the automatic conversion from Glade
>> files to GTK Builder xml, the same thing happened to some other bit as well
>> that needed to be manually restored. I can reproduce this, and will take a
>> look at it.
>
> Is there anything I can do to enable those plugin(s) without running
> pytrainer?

Yes, you can edit the conf.xml files under .pytrainer/plugins to
enable/disable them. garmintools_full and garmin-hr are the magic
plugins.

Actually fixing the bug is apparently more involved than I would have
expected, GTK has re-done the menu system at least twice since the
original code was written (the new version that we just converted to has
been deprecated as well). I'd like to get this fixed for the next
release anyway.

-- 
Arto Jantunen

**Comment by viiru-** [comment]
Andreas <notifications@github.com> writes:
> One more thing:
> `laptrigger VARCHAR(9)` is too short. My laps table holds the values time,
> manual and laptrigger. "laptrigger" has 10 characters.
>
> It doesn't harm in sqlite as it uses TEXT here, but it should be fixed while
> you clean the database schema.

Hmm. Interesting. I didn't change this, it has always been buggy. The
original code has the table defined like this:

 "laps":{        "id_lap": "integer primary key autoincrement",
                 "record": "integer",
                 "lap_number": "integer",
                 "elapsed_time": "varchar(20)",
                 "distance": "float",
                 "start_lat": "float",
                 "start_lon": "float",
                 "end_lat": "float",
                 "end_lon": "float",
                 "calories": "int",
                 "intensity": "varchar(7)",
                 "laptrigger": "varchar(9)",
                 "max_speed": "float",
                 "avg_hr": "int",
                 "max_hr": "int",
                 "comments":"text",
                 },

Also, could you start creating separate issues for all the different
bugs you find, so that they don't get lost in the clutter?

-- 
Arto Jantunen

**Comment by a-mair** [comment]
> Yes, you can edit the conf.xml files under .pytrainer/plugins to enable/disable them. garmintools_full and garmin-hr are the magic plugins. Actually fixing the bug is apparently more involved than I would have expected, GTK has re-done the menu system at least twice since the original code was written (the new version that we just converted to has been deprecated as well). I'd like to get this fixed for the next release anyway.

I got it working by removing the plugin folder's content now pytrainer runs. Setting "status" to "1" in each subfolder's conf.xml didn't work.

**Comment by a-mair** [comment]
>  Also, could you start creating separate issues for all the different bugs you find, so that they don't get lost in the clutter?

Sure, sorry for that. I've created [`laptrigger VARCHAR(9)` is too short](https://github.com/pytrainer/pytrainer/issues/143)

**Comment by viiru-** [comment]
Andreas <notifications@github.com> writes:
>> Yes, you can edit the conf.xml files under .pytrainer/plugins to
> enable/disable them. garmintools_full and garmin-hr are the magic
> plugins. Actually fixing the bug is apparently more involved than I would have
> expected, GTK has re-done the menu system at least twice since the original
> code was written (the new version that we just converted to has been
> deprecated as well). I'd like to get this fixed for the next release anyway.
>
> I got it working by removing the plugin folder's content now pytrainer
> runs. Setting "status" to "1" in each subfolder's conf.xml didn't
> work.

Settings status to "0" (as in disabled) would have worked, though.

-- 
Arto Jantunen

**Comment by a-mair** [comment]
> I would probably accept reasonably non-invasive patches doing this. I'm not sure how to hook between specific migrations, though. I assume there will be problems if we try to do this before running the other 14 migrations. Also keeping in mind that this should only be done sqlite databases (if there are Mysql users they don't need this, Mysql has alter table and doesn't do the "create temp table, move data, create new table" dance that is failing).

I think that if anybody else will face that problem all information to fix it can be found here.

> Any hints on what is special about your systems that get this alternative column order? Could we try to detect that?

Sure. It's a Gentoo system running pytrainer for 7 years.

**Comment by privong** [comment]
@a-mair Thanks for posting your sqlite database fix. That seems to have worked for getting my pytrainer instance working again.

**Comment by avtobiff** [comment]
Is this still an issue?
Something that needs to be fixed for 2.0?

**Comment by a-mair** [comment]
@avtobiff I didn't follow the latest pytrainer commits so I don't know if it's still an issue.
I fixed it locally like I've written [here](https://github.com/pytrainer/pytrainer/issues/140#issuecomment-385318134).

**Comment by viiru-** [comment]
This issue is caused by the combination of three problems:

1. Before version 1.12.0 pytrainer created database tables with columns in "random" order (order of dict keys, so depends on who built the python binary running it and with what options)
2. Sqlite does not support altering tables after creation, so it must be emulated by using temporary tables
3. Migrate uses "SELECT * FROM orig_table INTO temp_table" to do that, making it critical that the columns are in a fixed order (which they are not for tables created by old pytrainer versions)

Issue 1. has been fixed, since 1.12.0 the columns are always created in the same order. For the other two issues I don't think anything has been done or will be done. So users that have created their databases with an older release and upgraded to 1.12.0 or later can still hit this issue, but there isn't much we can do about that at this point.

My plan was to leave this issue open for now to make it easier for anyone suffering from this to find the (manual) solution @a-mair has described.
