### ISSUE TITLE
pytrainer doesn't start any more, 

### ISSUE THREAD

**Issue by iramia** [pytrainer/pytrainer#157]
Hi,
I've recently upgraded to Ubuntu 18:04 from 16:04. pytrainer (from the ubuntu repos) doesn't start any more. Now I reinstalled it from github, but it still doesn't start, missing the "canberra-gtk-module". It is there, though!?
Any ideas?
Thanks.

-----------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------
$ pytrainer
running pytrainer from egg installation
data_path: /usr/share/pytrainer/
gettext_path: /usr/share/locale
site_path: /usr/lib/python2.7/site-packages
Gtk-Message: 12:44:56.382: Failed to load module "canberra-gtk-module"
Traceback (most recent call last):
  File "/usr/bin/pytr", line 97, in <module>
    main()
  File "/usr/bin/pytr", line 93, in main
    from pytrainer.main import pyTrainer
  File "/usr/lib/python2.7/dist-packages/pytrainer/main.py", line 40, in <module>
    from gui.windowmain import Main
  File "/usr/lib/python2.7/dist-packages/pytrainer/gui/windowmain.py", line 38, in <module>
    from pytrainer.recordgraph import RecordGraph
  File "/usr/lib/python2.7/dist-packages/pytrainer/recordgraph.py", line 20, in <module>
    from gui.drawArea import DrawArea
  File "/usr/lib/python2.7/dist-packages/pytrainer/gui/drawArea.py", line 22, in <module>
    from matplotlib.backends.backend_gtkagg import FigureCanvasGTKAgg as FigureCanvasGTK
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_gtkagg.py", line 14, in <module>
    from matplotlib.backends.backend_gtk import (
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_gtk.py", line 35, in <module>
    from matplotlib.backends.backend_gdk import RendererGDK, FigureCanvasGDK
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_gdk.py", line 33, in <module>
    from matplotlib.backends._backend_gdk import pixbuf_get_pixels_array
ImportError: No module named _backend_gdk
-----------------------------------------------------------------------------------------------------
$ locate libcanberra-gtk-module.so
/usr/lib/x86_64-linux-gnu/gtk-3.0/modules/libcanberra-gtk-module.so
-----------------------------------------------------------------------------------------------------
Description:	Ubuntu 18.04 LTS
Release:	18.04

**Comment by viiru-** [comment]
This issue is a duplicate of #114. Matplotlib is built without support for GTK version 2. This is fixed in current git master, which has been ported to use GTK 3.

**Comment by iramia** [comment]
Hi,
thanks.

I've pulled the git master,and compiled which seemed to go fine, but then got a different error when trying to run:

_~/Programs/pytrainer$ sudo python setup.py install
[sudo] password for kira: 
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'zip_safe'
  warnings.warn(msg)
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'test_suite'
  warnings.warn(msg)
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'tests_require'
  warnings.warn(msg)
running install
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/pytrainer
copying pytrainer/save.py -> build/lib.linux-x86_64-2.7/pytrainer[
[....]
creating /usr/local/share/locale/sv
creating /usr/local/share/locale/sv/LC_MESSAGES
copying locale/sv/LC_MESSAGES/pytrainer.mo -> /usr/local/share/locale/sv/LC_MESSAGES
creating /usr/local/share/pixmaps
copying pytrainer.png -> /usr/local/share/pixmaps/
creating /usr/local/share/applications
copying pytrainer.desktop -> /usr/local/share/applications/
running install_egg_info
Writing /usr/local/lib/python2.7/dist-packages/pytrainer-1.12.2.egg-info_



:~/Programs/pytrainer$ pytrainer -i
running pytrainer from egg installation
data_path: /usr/local/share/pytrainer/
gettext_path: /usr/local/share/locale
site_path: /usr/local/lib/python2.7/site-packages

(pytrainer:23816): Gtk-WARNING **: 10:49:04.526: GtkFrame does not have a child property called padding

(pytrainer:23816): Gtk-WARNING **: 10:49:04.527: GtkFrame does not have a child property called expand

(pytrainer:23816): Gtk-WARNING **: 10:49:04.527: GtkFrame does not have a child property called fill

(pytrainer:23816): Gtk-WARNING **: 10:49:04.527: GtkFrame does not have a child property called position
Traceback (most recent call last):
  File "/usr/local/bin/pytrainer", line 98, in <module>
    main()
  File "/usr/local/bin/pytrainer", line 95, in main
    pytrainer = pyTrainer(None, data_path)
  File "/usr/local/lib/python2.7/dist-packages/pytrainer/main.py", line 108, in __init__
    self.loadPlugins()
  File "/usr/local/lib/python2.7/dist-packages/pytrainer/main.py", line 200, in loadPlugins
    self.windowmain.addImportPlugin(txtbutton)
  File "/usr/local/lib/python2.7/dist-packages/pytrainer/gui/windowmain.py", line 243, in addImportPlugin
    self.menuitem1_menu.insert(button,3)
  File "/usr/local/lib/python2.7/dist-packages/pytrainer/gui/SimpleGladeApp.py", line 53, in __getattr__
    raise AttributeError(data_name)
AttributeError: menuitem1_menu

**Comment by viiru-** [comment]
iramia <notifications@github.com> writes:
> Hi,
> thanks.
>
> I've pulled the git master,and compiled which seemed to go fine, but then got a different error when trying to run:
>
> _~/Programs/pytrainer$ sudo python setup.py install
> [sudo] password for kira: 
> /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'zip_safe'
>   warnings.warn(msg)
> /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
>   warnings.warn(msg)
> /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'test_suite'
>   warnings.warn(msg)
> /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'tests_require'
>   warnings.warn(msg)
> running install
> running build
> running build_py
> creating build
> creating build/lib.linux-x86_64-2.7
> creating build/lib.linux-x86_64-2.7/pytrainer
> copying pytrainer/save.py -> build/lib.linux-x86_64-2.7/pytrainer[
> [....]
> creating /usr/local/share/locale/sv
> creating /usr/local/share/locale/sv/LC_MESSAGES
> copying locale/sv/LC_MESSAGES/pytrainer.mo -> /usr/local/share/locale/sv/LC_MESSAGES
> creating /usr/local/share/pixmaps
> copying pytrainer.png -> /usr/local/share/pixmaps/
> creating /usr/local/share/applications
> copying pytrainer.desktop -> /usr/local/share/applications/
> running install_egg_info
> Writing /usr/local/lib/python2.7/dist-packages/pytrainer-1.12.2.egg-info_
>
>
>
> :~/Programs/pytrainer$ pytrainer -i
> running pytrainer from egg installation
> data_path: /usr/local/share/pytrainer/
> gettext_path: /usr/local/share/locale
> site_path: /usr/local/lib/python2.7/site-packages
>
> (pytrainer:23816): Gtk-WARNING **: 10:49:04.526: GtkFrame does not have a child property called padding
>
> (pytrainer:23816): Gtk-WARNING **: 10:49:04.527: GtkFrame does not have a child property called expand
>
> (pytrainer:23816): Gtk-WARNING **: 10:49:04.527: GtkFrame does not have a child property called fill
>
> (pytrainer:23816): Gtk-WARNING **: 10:49:04.527: GtkFrame does not have a child property called position
> Traceback (most recent call last):
>   File "/usr/local/bin/pytrainer", line 98, in <module>
>     main()
>   File "/usr/local/bin/pytrainer", line 95, in main
>     pytrainer = pyTrainer(None, data_path)
>   File "/usr/local/lib/python2.7/dist-packages/pytrainer/main.py", line 108, in __init__
>     self.loadPlugins()
>   File "/usr/local/lib/python2.7/dist-packages/pytrainer/main.py", line 200, in loadPlugins
>     self.windowmain.addImportPlugin(txtbutton)
>   File "/usr/local/lib/python2.7/dist-packages/pytrainer/gui/windowmain.py", line 243, in addImportPlugin
>     self.menuitem1_menu.insert(button,3)
>   File "/usr/local/lib/python2.7/dist-packages/pytrainer/gui/SimpleGladeApp.py", line 53, in __getattr__
>     raise AttributeError(data_name)
> AttributeError: menuitem1_menu

That is issue #144, which has not yet been fixed (as far as I can tell
the relevant functionality needs a rewrite, modifying the menus like
that on the fly does not seem possible with GTK3).

As mentioned there, you can disable the offending plugins by editing the
xml which will make pytrainer start (that won't help you if you need
those plugins, though).

-- 
Arto Jantunen

**Comment by iramia** [comment]
Thanks, I understand. I appreciate the work you are doing.
There was no status variable in the conf.xml files. 
Removing the conf.xml files, recompiling and re-running produces the same error. Also removing the whole plugin folder (for the mentioned garmintools_full and garmin-hr) did not help, the error message didn't change.
