### ISSUE TITLE
Unable to import gpx files exported from movescount

### ISSUE THREAD

**Issue by privong** [pytrainer/pytrainer#166]
In pytrainer v2.0.0rc1 and 1.12.2 I am unable to import GPX files into pytrainer that have been exported from the Suunto Movescount webpage.

After selecting `File`->`Import` this error is printed to the console:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gi/overrides/Gtk.py", line 110, in _builder_connect_callback
    handler, args = _extract_handler_and_args(obj_or_map, handler_name)
  File "/usr/lib/python2.7/site-packages/gi/overrides/Gtk.py", line 90, in _extract_handler_and_args
    raise AttributeError('Handler %s not found' % handler_name)
AttributeError: Handler on_win_importdata_destroy_event not found
```
After adding the file the "Select Activities to Import" dialog shows an activity with the correct duration, but no distance. When I then press "Import", a "Modify details before importing" dialog appears. But this is printed to the console:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pytrainer/gui/windowimportdata.py", line 642, in on_buttonFileImport_clicked
    importedActivities = self.importSelectedActivities(selectedActivities)
  File "/usr/lib/python2.7/site-packages/pytrainer/gui/windowimportdata.py", line 476, in importSelectedActivities
    result = self.pytrainer_main.record.newMultiRecord(activities)
  File "/usr/lib/python2.7/site-packages/pytrainer/record.py", line 58, in newMultiRecord
    self.recordwindow.populateMultiWindow(activities)
  File "/usr/lib/python2.7/site-packages/pytrainer/gui/windowrecord.py", line 199, in populateMultiWindow
    self.show_treeviewEntries_row(0)
  File "/usr/lib/python2.7/site-packages/pytrainer/gui/windowrecord.py", line 554, in show_treeviewEntries_row
    self.update_activity_data(row, gpx_file, sport)
  File "/usr/lib/python2.7/site-packages/pytrainer/gui/windowrecord.py", line 483, in update_activity_data
    gpx_summary, laps = self.parent.summaryFromGPX(gpx_file, (sport,""))
  File "/usr/lib/python2.7/site-packages/pytrainer/record.py", line 277, in summaryFromGPX
    laps = self.lapsFromGPX(gpx)
  File "/usr/lib/python2.7/site-packages/pytrainer/record.py", line 184, in lapsFromGPX
    gpxLaps = gpx.getLaps()
  File "/usr/lib/python2.7/site-packages/pytrainer/lib/gpx.py", line 175, in getLaps
    lat = endPoint.get("lat")
AttributeError: 'NoneType' object has no attribute 'get'
```

The "Modify details..." dialog has the correct time, but no distance or distance-derived information. Pressing "Ok" in this dialog appears to do nothing. But when I press "Cancel" the dialog box goes away. The console then has this (seemingly copied as many times as I'd pressed "Ok"):

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pytrainer/gui/windowrecord.py", line 246, in on_accept_clicked
    self.update_activity_data(row, activity["rcd_gpxfile"], activity["rcd_sport"])
  File "/usr/lib/python2.7/site-packages/pytrainer/gui/windowrecord.py", line 483, in update_activity_data
    gpx_summary, laps = self.parent.summaryFromGPX(gpx_file, (sport,""))
  File "/usr/lib/python2.7/site-packages/pytrainer/record.py", line 277, in summaryFromGPX
    laps = self.lapsFromGPX(gpx)
  File "/usr/lib/python2.7/site-packages/pytrainer/record.py", line 184, in lapsFromGPX
    gpxLaps = gpx.getLaps()
  File "/usr/lib/python2.7/site-packages/pytrainer/lib/gpx.py", line 175, in getLaps
    lat = endPoint.get("lat")
AttributeError: 'NoneType' object has no attribute 'get'
```

A copy of the GPX file is available here: http://privon.com/upload/test.gpx

**Comment by segmentierungsfehler** [comment]
In the test.gpx from movescount there is a <extensions><gpxdata:lap>...</gpxdata:lap></extensions> at
the end of the file. As a workaround you may remove this lines (starting from line 954 to 973) and import to pytrainer should work again. Pytrainer expects more entries in gpxdata:lap and is therefore complaining.

**Comment by privong** [comment]
For what it's worth, `.fit` files generated by movescount import fine. So I've switched to using those.

Also, movescount itself will be discontinued sometime after summer 2020(https://www.suunto.com/en-us/Content-pages/digital-service-transition/). I don't know if the replacement will use the same gpx generation routines, so it's unclear to me if this bug is of long-term importance.

**Comment by ulrichard** [comment]
I get a similar error when trying to import gpx files from
https://open-store.io/app/activitytracker.cwayne18

**Comment by privong** [comment]
Movescount does not exist anymore, so I'm going to close this.
