### ISSUE TITLE
TypeError: Argument must be bytes or unicode, got 'NoneType'

### ISSUE THREAD

**Issue by jtojnar** [pytrainer/pytrainer#173]
When I switch to the Sports tab in the preferences, I see the following error:

```
Traceback (most recent call last):
  File "/home/jtojnar/projects/pytrainer/pytrainer/gui/windowprofile.py", line 180, in on_switch_page
    self.saveOptions()
  File "/home/jtojnar/projects/pytrainer/pytrainer/gui/windowprofile.py", line 166, in saveOptions
    self.parent.setProfile(list_options)
  File "/home/jtojnar/projects/pytrainer/pytrainer/profile.py", line 256, in setProfile
    self.setValue("pytraining",option,value,delay_write=True)
  File "/home/jtojnar/projects/pytrainer/pytrainer/profile.py", line 247, in setValue
    self.xml_tree.getroot().set(variable, value)
  File "src/lxml/etree.pyx", line 813, in lxml.etree._Element.set
  File "src/lxml/apihelpers.pxi", line 570, in lxml.etree._setAttributeValue
  File "src/lxml/apihelpers.pxi", line 1437, in lxml.etree._utf8
TypeError: Argument must be bytes or unicode, got 'NoneType'
```

I have no Sports defined.

**Comment by jtojnar** [comment]
Same thing when saving the preferences without switching to Sports tab.

Also I am using Python 3.

**Comment by avtobiff** [comment]
I can't reproduce this behaviour. Can you provide an example config setup
where this occurs?

**Comment by jtojnar** [comment]
I can still reproduce in a9bfb8bd3264fac19bf4fca62fc953bd48292434. I deleted the `~/.pytrainer` directory prior to starting the app.

**Comment by avtobiff** [comment]
I've tried with different setups: no confdir, changing `HOME` etc; to no avail.

I still can't reproduce this...

**Comment by jtojnar** [comment]
I can no longer reproduce this.
