### ISSUE TITLE
SuSE Leap 15.2 Install failed

### ISSUE THREAD

**Issue by fmartin2912** [pytrainer/pytrainer#219]
Here comes the log from setup.py install (only the part which fails).
What's left to do to install pytrainer? 

(process:6789): Gdk-CRITICAL **: 15:45:55.162: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Traceback (most recent call last):
  File "/usr/local/bin/pytrainer", line 4, in <module>
    __import__('pkg_resources').run_script('pytrainer==2.0.1', 'pytrainer')
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 661, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1441, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/site-packages/pytrainer-2.0.1-py2.7.egg/EGG-INFO/scripts/pytrainer", line 98, in <module>
    main()
  File "/usr/local/lib/python2.7/site-packages/pytrainer-2.0.1-py2.7.egg/EGG-INFO/scripts/pytrainer", line 94, in main
    from pytrainer.main import pyTrainer
  File "/usr/local/lib/python2.7/site-packages/pytrainer-2.0.1-py2.7.egg/pytrainer/main.py", line 44, in <module>
    from .gui.windowmain import Main
  File "/usr/local/lib/python2.7/site-packages/pytrainer-2.0.1-py2.7.egg/pytrainer/gui/windowmain.py", line 39, in <module>
    from pytrainer.recordgraph import RecordGraph
  File "/usr/local/lib/python2.7/site-packages/pytrainer-2.0.1-py2.7.egg/pytrainer/recordgraph.py", line 20, in <module>
    from .gui.drawArea import DrawArea
  File "/usr/local/lib/python2.7/site-packages/pytrainer-2.0.1-py2.7.egg/pytrainer/gui/drawArea.py", line 22, in <module>
    from matplotlib.backends.backend_gtk3agg import FigureCanvasGTK3Agg as FigureCanvasGTK
  File "/usr/lib64/python2.7/site-packages/matplotlib/backends/backend_gtk3agg.py", line 9, in <module>
    from . import backend_agg, backend_gtk3
  File "/usr/lib64/python2.7/site-packages/matplotlib/backends/backend_gtk3.py", line 32, in <module>
    cursors.MOVE          : Gdk.Cursor.new(Gdk.CursorType.FLEUR),
TypeError: constructor returned NULL

**Comment by hjerning** [comment]
This is a matplotlib issue, https://github.com/matplotlib/matplotlib/issues/19405, solved in matplotlib 3.4.0.
