### ISSUE TITLE
Ubuntu 20.4 , dose not work out of box !

### ISSUE THREAD

**Issue by joni73** [pytrainer/pytrainer#228]
joni@mpi1:~$ pytrainer
running pytrainer from egg installation
data_path: /usr/local/lib/python3.8/dist-packages/pytrainer-2.0.1-py3.8.egg/share/pytrainer/
gettext_path: /usr/local/lib/python3.8/dist-packages/pytrainer-2.0.1-py3.8.egg/share/locale
site_path: /usr/local/lib/python3.8/dist-packages/pytrainer-2.0.1-py3.8.egg/lib/python3.8/site-packages

(pytrainer:3785990): Gtk-WARNING **: 10:25:04.700: GtkFrame does not have a child property called padding

(pytrainer:3785990): Gtk-WARNING **: 10:25:04.702: GtkFrame does not have a child property called expand

(pytrainer:3785990): Gtk-WARNING **: 10:25:04.702: GtkFrame does not have a child property called fill

(pytrainer:3785990): Gtk-WARNING **: 10:25:04.702: GtkFrame does not have a child property called position
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pytrainer-2.0.1-py3.8.egg/pytrainer/gui/windowimportdata.py", line 642, in on_buttonFileImport_clicked
    importedActivities = self.importSelectedActivities(selectedActivities)
  File "/usr/local/lib/python3.8/dist-packages/pytrainer-2.0.1-py3.8.egg/pytrainer/gui/windowimportdata.py", line 475, in importSelectedActivities
    result = self.pytrainer_main.record.newMultiRecord(activities)
  File "/usr/local/lib/python3.8/dist-packages/pytrainer-2.0.1-py3.8.egg/pytrainer/record.py", line 60, in newMultiRecord
    self.recordwindow.populateMultiWindow(activities)
  File "/usr/local/lib/python3.8/dist-packages/pytrainer-2.0.1-py3.8.egg/pytrainer/gui/windowrecord.py", line 200, in populateMultiWindow
    self.show_treeviewEntries_row(0)
  File "/usr/local/lib/python3.8/dist-packages/pytrainer-2.0.1-py3.8.egg/pytrainer/gui/windowrecord.py", line 566, in show_treeviewEntries_row
    self.update_activity_data(row, gpx_file, sport)
  File "/usr/local/lib/python3.8/dist-packages/pytrainer-2.0.1-py3.8.egg/pytrainer/gui/windowrecord.py", line 495, in update_activity_data
    gpx_summary, laps = self.parent.summaryFromGPX(gpx_file, (sport,""))
  File "/usr/local/lib/python3.8/dist-packages/pytrainer-2.0.1-py3.8.egg/pytrainer/record.py", line 281, in summaryFromGPX
    lap_avg_hr, lap_max_hr = self.hrFromLaps(laps)
  File "/usr/local/lib/python3.8/dist-packages/pytrainer-2.0.1-py3.8.egg/pytrainer/record.py", line 226, in hrFromLaps
    lap_avg_hr = int(round(ponderate_hr/total_duration)) # ceil?, floor?, round?
ZeroDivisionError: float division by zero
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pytrainer-2.0.1-py3.8.egg/pytrainer/gui/windowrecord.py", line 247, in on_accept_clicked
    self.update_activity_data(row, activity["rcd_gpxfile"], activity["rcd_sport"])
  File "/usr/local/lib/python3.8/dist-packages/pytrainer-2.0.1-py3.8.egg/pytrainer/gui/windowrecord.py", line 495, in update_activity_data
    gpx_summary, laps = self.parent.summaryFromGPX(gpx_file, (sport,""))
  File "/usr/local/lib/python3.8/dist-packages/pytrainer-2.0.1-py3.8.egg/pytrainer/record.py", line 281, in summaryFromGPX
    lap_avg_hr, lap_max_hr = self.hrFromLaps(laps)
  File "/usr/local/lib/python3.8/dist-packages/pytrainer-2.0.1-py3.8.egg/pytrainer/record.py", line 226, in hrFromLaps
    lap_avg_hr = int(round(ponderate_hr/total_duration)) # ceil?, floor?, round?
ZeroDivisionError: float division by zero
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pytrainer-2.0.1-py3.8.egg/pytrainer/gui/windowrecord.py", line 247, in on_accept_clicked
    self.update_activity_data(row, activity["rcd_gpxfile"], activity["rcd_sport"])
  File "/usr/local/lib/python3.8/dist-packages/pytrainer-2.0.1-py3.8.egg/pytrainer/gui/windowrecord.py", line 495, in update_activity_data
    gpx_summary, laps = self.parent.summaryFromGPX(gpx_file, (sport,""))
  File "/usr/local/lib/python3.8/dist-packages/pytrainer-2.0.1-py3.8.egg/pytrainer/record.py", line 281, in summaryFromGPX
    lap_avg_hr, lap_max_hr = self.hrFromLaps(laps)
  File "/usr/local/lib/python3.8/dist-packages/pytrainer-2.0.1-py3.8.egg/pytrainer/record.py", line 226, in hrFromLaps
    lap_avg_hr = int(round(ponderate_hr/total_duration)) # ceil?, floor?, round?
ZeroDivisionError: float division by zero
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pytrainer-2.0.1-py3.8.egg/pytrainer/gui/windowrecord.py", line 247, in on_accept_clicked
    self.update_activity_data(row, activity["rcd_gpxfile"], activity["rcd_sport"])
  File "/usr/local/lib/python3.8/dist-packages/pytrainer-2.0.1-py3.8.egg/pytrainer/gui/windowrecord.py", line 495, in update_activity_data
    gpx_summary, laps = self.parent.summaryFromGPX(gpx_file, (sport,""))
  File "/usr/local/lib/python3.8/dist-packages/pytrainer-2.0.1-py3.8.egg/pytrainer/record.py", line 281, in summaryFromGPX
    lap_avg_hr, lap_max_hr = self.hrFromLaps(laps)
  File "/usr/local/lib/python3.8/dist-packages/pytrainer-2.0.1-py3.8.egg/pytrainer/record.py", line 226, in hrFromLaps
    lap_avg_hr = int(round(ponderate_hr/total_duration)) # ceil?, floor?, round?
ZeroDivisionError: float division by zero
joni@mpi1:~$

**Comment by joni73** [comment]
2021-10-08 10:20:32,498|INFO|base|_log_info|SELECT records.id_record AS records_id_record, records.sport AS records_sport, records.average AS records_average, records.beats AS records_beats, records.calories AS records_calories, records.comments AS records_comments, records.date AS records_date, records.date_time_local AS records_date_time_local, records.date_time_utc AS records_date_time_utc, records.distance AS records_distance, records.duration AS records_duration, records.maxbeats AS records_maxbeats, records.maxpace AS records_maxpace, records.maxspeed AS records_maxspeed, records.pace AS records_pace, records.title AS records_title, records.unegative AS records_unegative, records.upositive AS records_upositive 
FROM records 
WHERE records.date_time_utc = ?
2021-10-08 10:20:32,499|INFO|base|_log_info|[generated in 0.00099s] ('2106-02-07T06:28:16Z',)
2021-10-08 10:20:38,126|INFO|base|_log_info|SELECT sports.id_sports AS sports_id_sports, sports.color AS sports_color, sports.max_pace AS sports_max_pace, sports.met AS sports_met, sports.name AS sports_name, sports.weight AS sports_weight 
FROM sports
2021-10-08 10:20:38,126|INFO|base|_log_info|[cached since 37.73s ago] ()
2021-10-08 10:20:38,186|INFO|base|_log_info|SELECT equipment.active AS equipment_active, equipment.description AS equipment_description, equipment.id AS equipment_id, equipment.life_expectancy AS equipment_life_expectancy, equipment.notes AS equipment_notes, equipment.prior_usage AS equipment_prior_usage 
FROM equipment 
WHERE equipment.active = 1
2021-10-08 10:20:38,186|INFO|base|_log_info|[generated in 0.00040s] ()
2021-10-08 10:20:38,217|INFO|gpx|_getValues|Lap distance: 19369.6900000 m | Duration: 0.0 s | Calories: 0 kcal
2021-10-08 10:20:38,217|INFO|gpx|_getValues|Laps - Distance: 19.37 km | Duration: 0 s | Calories: 0 kcal
2021-10-08 10:20:38,919|INFO|gpx|_getValues|Values - Distance: 19.37 km | Duration: 0 s | Calories: 0 kcal
2021-10-08 10:20:38,920|INFO|gpx|getLaps|Found time: 0.0000000, start lat: 60.9504614, start lon: 27.5912350, end lat: 60.9675521 end lon: 27.8333516 cal: 0 dist: 19369.6900000 
2021-10-08 10:20:38,920|INFO|gpx|getLaps|Intensity: active | Trigger: manual | Max speed: 0.0000000 | Average hr: None | Maximum hr: None
2021-10-08 10:21:22,050|INFO|gpx|_getValues|Lap distance: 19369.6900000 m | Duration: 0.0 s | Calories: 0 kcal
2021-10-08 10:21:22,050|INFO|gpx|_getValues|Laps - Distance: 19.37 km | Duration: 0 s | Calories: 0 kcal
2021-10-08 10:21:22,743|INFO|gpx|_getValues|Values - Distance: 19.37 km | Duration: 0 s | Calories: 0 kcal
2021-10-08 10:21:22,744|INFO|gpx|getLaps|Found time: 0.0000000, start lat: 60.9504614, start lon: 27.5912350, end lat: 60.9675521 end lon: 27.8333516 cal: 0 dist: 19369.6900000 
2021-10-08 10:21:22,745|INFO|gpx|getLaps|Intensity: active | Trigger: manual | Max speed: 0.0000000 | Average hr: None | Maximum hr: None
2021-10-08 10:21:25,676|INFO|gpx|_getValues|Lap distance: 19369.6900000 m | Duration: 0.0 s | Calories: 0 kcal
2021-10-08 10:21:25,677|INFO|gpx|_getValues|Laps - Distance: 19.37 km | Duration: 0 s | Calories: 0 kcal
2021-10-08 10:21:26,402|INFO|gpx|_getValues|Values - Distance: 19.37 km | Duration: 0 s | Calories: 0 kcal
2021-10-08 10:21:26,403|INFO|gpx|getLaps|Found time: 0.0000000, start lat: 60.9504614, start lon: 27.5912350, end lat: 60.9675521 end lon: 27.8333516 cal: 0 dist: 19369.6900000 
2021-10-08 10:21:26,403|INFO|gpx|getLaps|Intensity: active | Trigger: manual | Max speed: 0.0000000 | Average hr: None | Maximum hr: None
2021-10-08 10:21:26,777|INFO|gpx|_getValues|Lap distance: 19369.6900000 m | Duration: 0.0 s | Calories: 0 kcal
2021-10-08 10:21:26,778|INFO|gpx|_getValues|Laps - Distance: 19.37 km | Duration: 0 s | Calories: 0 kcal
2021-10-08 10:21:27,479|INFO|gpx|_getValues|Values - Distance: 19.37 km | Duration: 0 s | Calories: 0 kcal
2021-10-08 10:21:27,481|INFO|gpx|getLaps|Found time: 0.0000000, start lat: 60.9504614, start lon: 27.5912350, end lat: 60.9675521 end lon: 27.8333516 cal: 0 dist: 19369.6900000 
2021-10-08 10:21:27,481|INFO|gpx|getLaps|Intensity: active | Trigger: manual | Max speed: 0.0000000 | Average hr: None | Maximum hr: None
2021-10-08 10:21:36,758|INFO|gpx|_getValues|Lap distance: 19369.6900000 m | Duration: 0.0 s | Calories: 0 kcal
2021-10-08 10:21:36,758|INFO|gpx|_getValues|Laps - Distance: 19.37 km | Duration: 0 s | Calories: 0 kcal
2021-10-08 10:21:37,458|INFO|gpx|_getValues|Values - Distance: 19.37 km | Duration: 0 s | Calories: 0 kcal
2021-10-08 10:21:37,459|INFO|gpx|getLaps|Found time: 0.0000000, start lat: 60.9504614, start lon: 27.5912350, end lat: 60.9675521 end lon: 27.8333516 cal: 0 dist: 19369.6900000 
2021-10-08 10:21:37,459|INFO|gpx|getLaps|Intensity: active | Trigger: manual | Max speed: 0.0000000 | Average hr: None | Maximum hr: None
2021-10-08 10:21:37,816|INFO|gpx|_getValues|Lap distance: 19369.6900000 m | Duration: 0.0 s | Calories: 0 kcal
2021-10-08 10:21:37,817|INFO|gpx|_getValues|Laps - Distance: 19.37 km | Duration: 0 s | Calories: 0 kcal
2021-10-08 10:21:38,526|INFO|gpx|_getValues|Values - Distance: 19.37 km | Duration: 0 s | Calories: 0 kcal
2021-10-08 10:21:38,528|INFO|gpx|getLaps|Found time: 0.0000000, start lat: 60.9504614, start lon: 27.5912350, end lat: 60.9675521 end lon: 27.8333516 cal: 0 dist: 19369.6900000 
2021-10-08 10:21:38,528|INFO|gpx|getLaps|Intensity: active | Trigger: manual | Max speed: 0.0000000 | Average hr: None | Maximum hr: None
2021-10-08 10:21:38,541|INFO|gpx|_getValues|Lap distance: 19369.6900000 m | Duration: 0.0 s | Calories: 0 kcal
2021-10-08 10:21:38,541|INFO|gpx|_getValues|Laps - Distance: 19.37 km | Duration: 0 s | Calories: 0 kcal
2021-10-08 10:21:39,253|INFO|gpx|_getValues|Values - Distance: 19.37 km | Duration: 0 s | Calories: 0 kcal
2021-10-08 10:21:39,254|INFO|gpx|getLaps|Found time: 0.0000000, start lat: 60.9504614, start lon: 27.5912350, end lat: 60.9675521 end lon: 27.8333516 cal: 0 dist: 19369.6900000 
2021-10-08 10:21:39,254|INFO|gpx|getLaps|Intensity: active | Trigger: manual | Max speed: 0.0000000 | Average hr: None | Maximum hr: None
2021-10-08 10:21:39,272|INFO|gpx|_getValues|Lap distance: 19369.6900000 m | Duration: 0.0 s | Calories: 0 kcal
2021-10-08 10:21:39,273|INFO|gpx|_getValues|Laps - Distance: 19.37 km | Duration: 0 s | Calories: 0 kcal
2021-10-08 10:21:39,980|INFO|gpx|_getValues|Values - Distance: 19.37 km | Duration: 0 s | Calories: 0 kcal
2021-10-08 10:21:39,981|INFO|gpx|getLaps|Found time: 0.0000000, start lat: 60.9504614, start lon: 27.5912350, end lat: 60.9675521 end lon: 27.8333516 cal: 0 dist: 19369.6900000 
2021-10-08 10:21:39,982|INFO|gpx|getLaps|Intensity: active | Trigger: manual | Max speed: 0.0000000 | Average hr: None | Maximum hr: None
2021-10-08 10:22:01,089|INFO|base|_log_info|SELECT sports.id_sports AS sports_id_sports, sports.color AS sports_color, sports.max_pace AS sports_max_pace, sports.met AS sports_met, sports.name AS sports_name, sports.weight AS sports_weight 
FROM sports 
WHERE sports.name = ?
2021-10-08 10:22:01,089|INFO|base|_log_info|[cached since 120.6s ago] ('All Sports',)
2021-10-08 10:22:01,090|INFO|base|_log_info|SELECT sports.id_sports AS sports_id_sports, sports.color AS sports_color, sports.max_pace AS sports_max_pace, sports.met AS sports_met, sports.name AS sports_name, sports.weight AS sports_weight 
FROM sports 
WHERE sports.name = ?
2021-10-08 10:22:01,090|INFO|base|_log_info|[cached since 120.6s ago] ('All Sports',)
2021-10-08 10:22:01,091|INFO|base|_log_info|SELECT records.id_record AS records_id_record, records.sport AS records_sport, records.average AS records_average, records.beats AS records_beats, records.calories AS records_calories, records.comments AS records_comments, records.date AS records_date, records.date_time_local AS records_date_time_local, records.date_time_utc AS records_date_time_utc, records.distance AS records_distance, records.duration AS records_duration, records.maxbeats AS records_maxbeats, records.maxpace AS records_maxpace, records.maxspeed AS records_maxspeed, records.pace AS records_pace, records.title AS records_title, records.unegative AS records_unegative, records.upositive AS records_upositive, laps_1.avg_hr AS laps_1_avg_hr, laps_1.calories AS laps_1_calories, laps_1.comments AS laps_1_comments, laps_1.distance AS laps_1_distance, laps_1.elapsed_time AS laps_1_elapsed_time, laps_1.end_lat AS laps_1_end_lat, laps_1.end_lon AS laps_1_end_lon, laps_1.id_lap AS laps_1_id_lap, laps_1.intensity AS laps_1_intensity, laps_1.lap_number AS laps_1_lap_number, laps_1.laptrigger AS laps_1_laptrigger, laps_1.max_hr AS laps_1_max_hr, laps_1.max_speed AS laps_1_max_speed, laps_1.record AS laps_1_record, laps_1.start_lat AS laps_1_start_lat, laps_1.start_lon AS laps_1_start_lon 
FROM records LEFT OUTER JOIN laps AS laps_1 ON records.id_record = laps_1.record 
WHERE records.date = ? ORDER BY laps_1.lap_number
2021-10-08 10:22:01,091|INFO|base|_log_info|[cached since 120.7s ago] ('2021-09-01',)
2021-10-08 10:22:01,093|INFO|base|_log_info|SELECT records.id_record AS records_id_record, records.sport AS records_sport, records.average AS records_average, records.beats AS records_beats, records.calories AS records_calories, records.comments AS records_comments, records.date AS records_date, records.date_time_local AS records_date_time_local, records.date_time_utc AS records_date_time_utc, records.distance AS records_distance, records.duration AS records_duration, records.maxbeats AS records_maxbeats, records.maxpace AS records_maxpace, records.maxspeed AS records_maxspeed, records.pace AS records_pace, records.title AS records_title, records.unegative AS records_unegative, records.upositive AS records_upositive 
FROM records 
WHERE records.date BETWEEN ? AND ?
2021-10-08 10:22:01,093|INFO|base|_log_info|[cached since 120.7s ago] ('2021-09-01', '2021-09-30')
2021-10-08 10:22:01,094|INFO|base|_log_info|SELECT sports.id_sports AS sports_id_sports, sports.color AS sports_color, sports.max_pace AS sports_max_pace, sports.met AS sports_met, sports.name AS sports_name, sports.weight AS sports_weight 
FROM sports 
WHERE sports.name = ?
2021-10-08 10:22:01,094|INFO|base|_log_info|[cached since 120.6s ago] ('All Sports',)
2021-10-08 10:22:01,095|INFO|base|_log_info|SELECT records.id_record AS records_id_record, records.sport AS records_sport, records.average AS records_average, records.beats AS records_beats, records.calories AS records_calories, records.comments AS records_comments, records.date AS records_date, records.date_time_local AS records_date_time_local, records.date_time_utc AS records_date_time_utc, records.distance AS records_distance, records.duration AS records_duration, records.maxbeats AS records_maxbeats, records.maxpace AS records_maxpace, records.maxspeed AS records_maxspeed, records.pace AS records_pace, records.title AS records_title, records.unegative AS records_unegative, records.upositive AS records_upositive, laps_1.avg_hr AS laps_1_avg_hr, laps_1.calories AS laps_1_calories, laps_1.comments AS laps_1_comments, laps_1.distance AS laps_1_distance, laps_1.elapsed_time AS laps_1_elapsed_time, laps_1.end_lat AS laps_1_end_lat, laps_1.end_lon AS laps_1_end_lon, laps_1.id_lap AS laps_1_id_lap, laps_1.intensity AS laps_1_intensity, laps_1.lap_number AS laps_1_lap_number, laps_1.laptrigger AS laps_1_laptrigger, laps_1.max_hr AS laps_1_max_hr, laps_1.max_speed AS laps_1_max_speed, laps_1.record AS laps_1_record, laps_1.start_lat AS laps_1_start_lat, laps_1.start_lon AS laps_1_start_lon 
FROM records LEFT OUTER JOIN laps AS laps_1 ON records.id_record = laps_1.record 
WHERE records.date = ? ORDER BY laps_1.lap_number
2021-10-08 10:22:01,095|INFO|base|_log_info|[cached since 120.7s ago] ('2021-09-01',)
2021-10-08 10:23:31,254|WARNING|warnings|_showwarnmsg|/usr/local/lib/python3.8/dist-packages/pytrainer-2.0.1-py3.8.egg/pytrainer/gui/windowmain.py:1194: SAWarning: TypeDecorator ForcedInteger() will not produce a cache key because the ``cache_ok`` flag is not set to True.  Set this flag to True if this type object's state is safe to use in a cache key, or False to disable this warning.
  for i in record_list:

2021-10-08 10:24:14,443|ERROR|windowimportdata|init_gpsdevice_tab|GPS Device import not yet implemented
2021-10-08 10:25:17,556|ERROR|windowimportdata|init_gpsdevice_tab|GPS Device import not yet implemented
2021-10-08 10:47:16,324|ERROR|windowimportdata|init_gpsdevice_tab|GPS Device import not yet implemented
2021-10-08 10:48:50,709|ERROR|windowimportdata|init_gpsdevice_tab|GPS Device import not yet implemented

**Comment by joni73** [comment]
So, tried apt-get install not work, github, both python2 and python3,...
If i import it creates window where it ask actually information it should got from .fit file.

As I understand could this be packing related problem,... what ever library it need's I can not figure out whatb library is wrong.

**Comment by joni73** [comment]
I 'am inporting files from oruxmaps.
