### ISSUE TITLE
can not import from Forerunner 305

### ISSUE THREAD

**Issue by tobiasdf** [pytrainer/pytrainer#32]
Hi, 
i can not import my Garmin Forerunner 305 logs anymore. 
It looks like it imports some some data, but it seems like it imports wrong information or the dump file gets converted wrong.
It is right, that the watch has 3 logs stored inside, check the log.
Is there any way to get the import in pytrainer working again ?

pytrainer -i
running pytrainer from egg installation
data_path: /usr/local/share/pytrainer/
gettext_path: /usr/local/share/locale
site_path: /usr/local/lib/python2.7/site-packages
ERROR:root:Failed when retrieving Min Heartrate value: invalid literal for int() with base 10: ''
INFO:root:Setting Min Heartrate to default value: 65
INFO:root:Initializing data. Data state is: 'CURRENT'.
INFO:root:Loading plugin Garmin via garmintools
INFO:root:Found Forerunner305 Software Version 2.90
INFO:root:Found files: 38
INFO:root:Retrieved 38 entries from GPS device
INFO:root:Discarding entries older than 365 days
INFO:root:Dumping 28 binary files found
INFO:root:Starting import. Comparison will be made with 195 seconds interval
INFO:root:Marking /home/user/.pytrainer/tmp/2014/03/20140327T190819.dump | 2014-03-27T18:08:22Z to import
INFO:root:Marking /home/user/.pytrainer/tmp/2014/04/20140413T095230.dump | 2014-04-13T07:52:30Z to import
INFO:root:Marking /home/user/.pytrainer/tmp/2014/04/20140404T161914.dump | 2014-04-04T14:19:13Z to import
INFO:root:Entries to import: 3
INFO:root:File exists. Size: 1334. Sport: Biking
INFO:root:Retrieving data from /home/user/.pytrainer/tmp/garmintools-0.gpx
INFO:root:Lap distance: 0.00000000 m | Duration: 4.04 s | Calories: 0 kcal
INFO:root:Laps - Distance: 0.00 km | Duration: 4 s | Calories: 0 kcal
INFO:root:Values - Distance: 0.01 km | Duration: 4 s | Calories: 0 kcal
INFO:root:Found time: 4.04, start lat: , start lon: , end lat:  end lon:  cal: 0 dist: 0.00000000 
INFO:root:Intensity: active | Trigger: manual | Max speed: 0.00000000 | Average hr: None | Maximum hr: None
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pytrainer/main.py", line 189, in runPlugin
    if self.record.importFromGPX(pluginFile, sport) is None:
  File "/usr/local/lib/python2.7/dist-packages/pytrainer/record.py", line 573, in importFromGPX
    entry_id = self.insertNewRecord(gpxFile, entry)
  File "/usr/local/lib/python2.7/dist-packages/pytrainer/record.py", line 190, in insertNewRecord
    (list_options, gpx_laps) = self.summaryFromGPX(gpxOrig, entry)
  File "/usr/local/lib/python2.7/dist-packages/pytrainer/record.py", line 288, in summaryFromGPX
    lap_avg_hr, lap_max_hr = self.hrFromLaps(laps)
  File "/usr/local/lib/python2.7/dist-packages/pytrainer/record.py", line 228, in hrFromLaps
    if int(lap['max_hr']) > lap_max_hr:
TypeError: int() argument must be a string or a number, not 'NoneType'

when i check the files :
/.pytrainer/tmp/2014/03/20140327T190819.dump  <-  file is not there, there is a 20140414T182449.dump instead 
/.pytrainer/tmp/2014/04/20140404T161914.dump <- data seems to be correct
/.pytrainer/tmp/2014/04/20140413T095230.dump <- data seems to be correct

**Comment by curiositry** [comment]
@avtobiff Seems to be. I am able to import Garmin Forerunner 305 data by fetching it with garmintools `garmin_save_runs`, converting the .gmn files to .tcx files manually with the script in https://github.com/cstrelioff/garmin-dev (`/path/to/gmn2tcx input.gmn > output.gmn.tcx`), and then importing the .tcx files manually.

When I try to use the garmintools plugin, I see "Test 1" and "Test 2" GPS devices, and get the following error when I click "Rescan":

```
running pytrainer from egg installation
gettext_path: /usr/share/locale
site_path: /usr/lib/python3.12/site-packages
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pytrainer/gui/windowimportdata.py", line 726, in on_comboboxDevice_changed
    self.detect_tools()
  File "/usr/lib/python3/dist-packages/pytrainer/gui/windowimportdata.py", line 212, in detect_tools
    if toolClass.isPresent():
       ^^^^^^^^^^^^^^^^^^^
AttributeError: 'garminfit' object has no attribute 'isPresent'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pytrainer/gui/windowimportdata.py", line 722, in on_buttonDeviceToolRescan_clicked
    self.detect_tools()
  File "/usr/lib/python3/dist-packages/pytrainer/gui/windowimportdata.py", line 212, in detect_tools
    if toolClass.isPresent():
       ^^^^^^^^^^^^^^^^^^^
AttributeError: 'garminfit' object has no attribute 'isPresent'
```
