### ISSUE TITLE
Support GPX files from Suunto Ambit watches

### ISSUE THREAD

**Issue by bubulle** [pytrainer/pytrainer#38]
GPX files from Suunto Ambit watches can't currently be imported properly. It seems that the distance is not correctly calculated

**Comment by privong** [comment]
@bubulle Just to be specific, are these generated directly from the Ambit or obtained via [Sunnto Movescount](http://www.movescount.com/]? I haven't been able to import into pytrainer GPX files whih were exported from movescount (in my case, for "moves" recorded with a Suunto Traverse).

I get the following error:
```
Activity incomplete.. /home/george/.pytrainer/tmp/gpx-0-0.gpx
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pytrainer/gui/windowrecord.py", line 241, in on_accept_clicked
    self.update_activity_data(row, activity["rcd_gpxfile"], activity["rcd_sport"])
  File "/usr/lib/python2.7/site-packages/pytrainer/gui/windowrecord.py", line 472, in update_activity_data
    gpx_summary, laps = self.parent.summaryFromGPX(gpx_file, (sport,""))
  File "/usr/lib/python2.7/site-packages/pytrainer/record.py", line 248, in summaryFromGPX
    gpx = Gpx(self.data_path,gpxOrig)
  File "/usr/lib/python2.7/site-packages/pytrainer/lib/gpx.py", line 110, in __init__
    self.Values = self._getValues()
  File "/usr/lib/python2.7/site-packages/pytrainer/lib/gpx.py", line 237, in _getValues
    self.calories += int(lapCalories)
TypeError: int() argument must be a string or a number, not 'NoneType'
```

Am wondering if this is the same issue or if I should open a new issue.

**Comment by bubulle** [comment]
Quoting George C. Privon (notifications@github.com):
> @bubulle Just to be specific, are these generated directly from the Ambit or obtained via [Sunnto Movescount](http://www.movescount.com/]? I haven't been able to import into pytrainer GPX files whih were exported from movescount (in my case, for "moves" recorded with a Suunto Traverse).


From memory, this was with GPX files obtanied from Movescount. I don't
have GPX files obtained from the Ambit because I'm using OpenAmbit and
it downloads "log" files that are specific to Suunto.

**Comment by privong** [comment]
Okay, I may try to tackle this, but can't commit to a timeline.
