### ISSUE TITLE
Installation on Debian sid

### ISSUE THREAD

**Issue by phatpat** [pytrainer/pytrainer#95]
Hi, thanks for you hard work, looking forward to using pytrainer again after a 2 year hiatus.

I get the following error when attempting to insall, I issue pytrainer -i and obtain the following. I googled and looked at the code but I am stuck.  Can you please help?

pytrainer -i
running pytrainer from egg installation
data_path: /usr/local/lib/python2.7/dist-packages/pytrainer-1.11.0.dev0-py2.7.egg/EGG-INFO/share/pytrainer/
gettext_path: /usr/local/lib/python2.7/dist-packages/pytrainer-1.11.0.dev0-py2.7.egg/EGG-INFO/share/locale
site_path: /usr/local/lib/python2.7/dist-packages/pytrainer-1.11.0.dev0-py2.7.egg/EGG-INFO/lib/python2.7/site-packages
Traceback (most recent call last):
  File "/usr/local/bin/pytrainer", line 4, in <module>
    __import__('pkg_resources').run_script('pytrainer==1.11.0.dev0', 'pytrainer')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1507, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/pytrainer-1.11.0.dev0-py2.7.egg/EGG-INFO/scripts/pytrainer", line 94, in <module>
    
  File "/usr/local/lib/python2.7/dist-packages/pytrainer-1.11.0.dev0-py2.7.egg/EGG-INFO/scripts/pytrainer", line 91, in main
    
  File "build/bdist.linux-i686/egg/pytrainer/main.py", line 74, in __init__
  File "build/bdist.linux-i686/egg/pytrainer/upgrade/data.py", line 30, in initialize_data
  File "build/bdist.linux-i686/egg/pytrainer/upgrade/migratedb.py", line 44, in __init__
  File "build/bdist.linux-i686/egg/pytrainer/upgrade/migratedb.py", line 96, in _get_resource_absolute_path
ValueError: Resource 'pytrainer/upgrade' could not be found

**Comment by viiru-** [comment]
I get a somewhat different error message, in my case the upgrade parts are installed but the data files aren't. I'll look into this, but due to other commitments it will take a few days.
